# Generated by Django 5.1.3 on 2024-12-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured_product',
        ),
    ]
